language: ruby
cache: bundler

rvm:
- 2.4.1

bundler_args: "--path=.bundle/gems"

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

  # GITHUB_TOKEN
  - secure: UwHs3veZj5VoWLtoxDhrGAJOqvAYpfzuJieaiYz2/A60XShykWGNEnaJ9AVbVYxzuU1S7RVaj6sMotiLKlo+c8kgCnuE0u59v6srL7/SuqBAxsISNcKkEnDJwygcwHerT4CCOrsFG8+/vZionoumA5LApoG3cIAsXnd6pPHqG1njG0WG9s0H98ox2vHBqkjftDZCbG8CvbMz8/6XndwSPSPToD4ZiyuqvASA/XN2MweWtfKr3HahM2R+d8dthOUdNcaQu+Kl8loy9IjUjmZ9A2e2IpdMUuVkiUdJzI7kciiVmOeO2g4EpaOVvFY0+qaG/6Gdw3Gchfjws2AgtyNFWRCbcuc4Kl8pI5NTfagr0u6kEdysVuVb6KtqYPgGE0dCcF6Qt+vYBRlTq80Iq9H5evrpxH0khjPtI2uA63BFUtdvG8T8RIZdsNQkaGZ9oTznqs1A8Nr84z5brbSQZM/pZhxCUe6Q5Wf06mx2mv7YO4hWqTempAztsMq7PjKPeKUUETEqlgPUFukQCXJ8s/eJOkt4W2owu18SLEUWbz2m2927jkjo7UB4PK7RajzLWF5Jfy+aPH0QGbuDnFoHFMAi7wgqgGbJ32kYIZspBAF6ripVTliZjSzz83Ute0RDR7KD/GX4XYjqxrz8cqdlPPVCivXOjfZ3G30ZMJdH/RmiGW4=

script: rake deploy

deploy:
  provider: pages
  skip_cleanup: true
  keep_history: false
  on:
    branch: travis
  name: BeerBuildBot
  email: buildbot@beer-garden.io
  github_token: "$GITHUB_TOKEN"
